### ISSUE TITLE
Botón Compartir no hace nada

### ISSUE THREAD

**Issue by ivrlx** [xavier-hernandez/react-wordle-spanish#9]
**Describe the bug**
Una vez has completado el wordle y sale la ventana de resumen si se hace click en compartir no funciona

**To Reproduce**
Completar el wordle del día en la web que publica el docker
Hacer click en compartir resultado

**Expected behavior**
Si se supone que debe funcionar como en la web https://wordle-es.xavier.cc/ debería copiar los resultados en el portapapeles

**Desktop (please complete the following information):**
 - OS: QNAP NAS (docker), Windows 10 (cliente)
 - Browser Chrome y Edge

**Smartphone (please complete the following information):**
 - Device: Xiaomi 12 Pro
 - OS: Android 12
 - Browser Chrome

**Comment by xavier-hernandez** [comment]
La rama, main, no estaba actualizado con mi sitio. Trata de bajar el codigo de nuevo.
